apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-pv-claim
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi