apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-pv-volume
spec:
  storageClassName: jenkins-pv
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"